//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birzha.Data_base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broker()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int Broker_ID { get; set; }
        public System.DateTime Registration_date { get; set; }
        public string Place_existing { get; set; }
        public string INN { get; set; }
        public string License_number { get; set; }
        public System.DateTime License_actuality { get; set; }
        public string Broker_name { get; set; }
        public string OGRN { get; set; }
        public string Adress { get; set; }
        public string Phone_number { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
