//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birzha.Data_base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Stock_ID { get; set; }
        public Nullable<decimal> Stock_cost { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Stocks_quantity_in_deal { get; set; }
        public Nullable<int> Deal { get; set; }
        public Nullable<decimal> Open { get; set; }
        public Nullable<decimal> Hight { get; set; }
        public Nullable<decimal> Low { get; set; }
        public Nullable<decimal> Close { get; set; }
        public Nullable<System.DateTime> PrevDate { get; set; }
    
        public virtual Company Company1 { get; set; }
        public virtual Deal Deal1 { get; set; }
    }
}
